// Tool to generate block state, biome registry data, and configuration tags
// from PrismarineJS minecraft-data and misode/mcmeta.
// Usage: go run tools/gen_registry/main.go
package main

import (
	"bytes"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"sort"
	"strings"
)

type block struct {
	ID           int     `json:"id"`
	Name         string  `json:"name"`
	MinStateID   int     `json:"minStateId"`
	MaxStateID   int     `json:"maxStateId"`
	DefaultState int     `json:"defaultState"`
	States       []state `json:"states"`
}

type state struct {
	Name      string   `json:"name"`
	Type      string   `json:"type"`
	NumValues int      `json:"num_values"`
	Values    []string `json:"values"`
}

type biome struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type item struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type entity struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type tagJSON struct {
	Values []string `json:"values"`
}

func main() {
	blocksData, err := os.ReadFile("tools/data/blocks.json")
	if err != nil {
		panic(err)
	}
	biomesData, err := os.ReadFile("tools/data/biomes.json")
	if err != nil {
		panic(err)
	}

	var blocks []block
	var biomes []biome
	json.Unmarshal(blocksData, &blocks)
	json.Unmarshal(biomesData, &biomes)

	var sb strings.Builder
	sb.WriteString("// Code generated by tools/gen_registry. DO NOT EDIT.\n")
	sb.WriteString("package world\n\n")

	// Block registry
	sb.WriteString("type blockDef struct {\n")
	sb.WriteString("\tMinStateID   int\n")
	sb.WriteString("\tDefaultState int\n")
	sb.WriteString("\tProperties   []propDef\n")
	sb.WriteString("}\n\n")
	sb.WriteString("type propDef struct {\n")
	sb.WriteString("\tName   string\n")
	sb.WriteString("\tValues []string\n")
	sb.WriteString("}\n\n")

	sb.WriteString("var blockRegistry = map[string]blockDef{\n")
	for _, b := range blocks {
		sb.WriteString(fmt.Sprintf("\t%q: {%d, %d, ", "minecraft:"+b.Name, b.MinStateID, b.DefaultState))
		if len(b.States) == 0 {
			sb.WriteString("nil},\n")
		} else {
			sb.WriteString("[]propDef{")
			for i, s := range b.States {
				if i > 0 {
					sb.WriteString(", ")
				}
				values := s.Values
				if s.Type == "bool" && len(values) == 0 {
					values = []string{"true", "false"}
				}
				sb.WriteString(fmt.Sprintf("{%q, []string{", s.Name))
				for j, v := range values {
					if j > 0 {
						sb.WriteString(", ")
					}
					sb.WriteString(fmt.Sprintf("%q", v))
				}
				sb.WriteString("}}")
			}
			sb.WriteString("}},\n")
		}
	}
	sb.WriteString("}\n\n")

	// Biome registry
	sort.Slice(biomes, func(i, j int) bool { return biomes[i].ID < biomes[j].ID })
	sb.WriteString("var biomeRegistry = map[string]int{\n")
	for _, b := range biomes {
		sb.WriteString(fmt.Sprintf("\t%q: %d,\n", "minecraft:"+b.Name, b.ID))
	}
	sb.WriteString("}\n")

	// Synced registries (must be sent during configuration even with Known Packs)
	registriesData, err := os.ReadFile("tools/data/registries.json")
	if err != nil {
		panic(err)
	}
	var registries map[string][]string
	json.Unmarshal(registriesData, &registries)

	syncedNames := []string{
		"dimension_type", "worldgen/biome", "chat_type", "damage_type",
		"banner_pattern", "painting_variant", "wolf_variant",
		"enchantment", "jukebox_song", "trim_pattern", "trim_material", "instrument",
	}

	sb.WriteString("\n// SyncedRegistries lists registries that must be sent via Registry Data during configuration.\n")
	sb.WriteString("// Entry keys are listed so the server can send has_data=false when Known Packs match.\n")
	sb.WriteString("var SyncedRegistries = []struct {\n")
	sb.WriteString("\tID      string\n")
	sb.WriteString("\tEntries []string\n")
	sb.WriteString("}{\n")

	totalEntries := 0
	for _, name := range syncedNames {
		entries, ok := registries[name]
		if !ok {
			continue
		}
		sort.Strings(entries)
		totalEntries += len(entries)
		sb.WriteString(fmt.Sprintf("\t{%q, []string{\n", "minecraft:"+name))
		for _, e := range entries {
			sb.WriteString(fmt.Sprintf("\t\t%q,\n", "minecraft:"+e))
		}
		sb.WriteString("\t}},\n")
	}
	sb.WriteString("}\n")

	os.WriteFile("internal/world/registry_generated.go", []byte(sb.String()), 0644)
	fmt.Printf("Generated registry: %d blocks, %d biomes, max state ID %d, %d synced registry entries\n",
		len(blocks), len(biomes), blocks[len(blocks)-1].MaxStateID, totalEntries)

	// === Generate tags ===
	generateTags(blocks, registries, syncedNames)

	// === Generate full registry data (for cross-version clients) ===
	generateFullRegistryData(syncedNames)
}

func generateTags(blocks []block, registries map[string][]string, syncedNames []string) {
	// Build ID maps for static registries
	blockIDs := make(map[string]int)
	for _, b := range blocks {
		blockIDs["minecraft:"+b.Name] = b.ID
	}

	itemIDs := loadNameIDMap("tools/data/items.json")
	entityIDs := loadNameIDMap("tools/data/entities.json")

	fluidIDs := map[string]int{
		"minecraft:empty":         0,
		"minecraft:flowing_water": 1,
		"minecraft:water":         2,
		"minecraft:flowing_lava":  3,
		"minecraft:lava":          4,
	}

	// Build ID maps for dynamic registries (index = position in sorted entry list)
	dynamicIDs := make(map[string]map[string]int)
	for _, name := range syncedNames {
		entries, ok := registries[name]
		if !ok {
			continue
		}
		sorted := make([]string, len(entries))
		copy(sorted, entries)
		sort.Strings(sorted)
		idMap := make(map[string]int)
		for i, e := range sorted {
			idMap["minecraft:"+e] = i
		}
		dynamicIDs[name] = idMap
	}

	// Tag registries to process
	type tagConfig struct {
		file     string
		registry string
		ids      map[string]int
	}
	configs := []tagConfig{
		{"tools/data/tags/block.json", "minecraft:block", blockIDs},
		{"tools/data/tags/item.json", "minecraft:item", itemIDs},
		{"tools/data/tags/fluid.json", "minecraft:fluid", fluidIDs},
		{"tools/data/tags/entity_type.json", "minecraft:entity_type", entityIDs},
		{"tools/data/tags/enchantment.json", "minecraft:enchantment", dynamicIDs["enchantment"]},
		{"tools/data/tags/biome.json", "minecraft:worldgen/biome", dynamicIDs["worldgen/biome"]},
		{"tools/data/tags/damage_type.json", "minecraft:damage_type", dynamicIDs["damage_type"]},
		{"tools/data/tags/painting_variant.json", "minecraft:painting_variant", dynamicIDs["painting_variant"]},
		{"tools/data/tags/banner_pattern.json", "minecraft:banner_pattern", dynamicIDs["banner_pattern"]},
		{"tools/data/tags/instrument.json", "minecraft:instrument", dynamicIDs["instrument"]},
	}

	var sb strings.Builder
	sb.WriteString("// Code generated by tools/gen_registry. DO NOT EDIT.\n")
	sb.WriteString("package world\n\n")
	sb.WriteString("// TagDef is a single tag group with resolved entry IDs.\n")
	sb.WriteString("type TagDef struct {\n")
	sb.WriteString("\tName    string\n")
	sb.WriteString("\tEntries []int32\n")
	sb.WriteString("}\n\n")
	sb.WriteString("// TagRegistryDef holds all tags for one registry.\n")
	sb.WriteString("type TagRegistryDef struct {\n")
	sb.WriteString("\tRegistry string\n")
	sb.WriteString("\tTags     []TagDef\n")
	sb.WriteString("}\n\n")
	sb.WriteString("// ConfigurationTags contains all resolved tags for the Update Tags configuration packet.\n")
	sb.WriteString("var ConfigurationTags = []TagRegistryDef{\n")

	totalTags := 0
	for _, cfg := range configs {
		data, err := os.ReadFile(cfg.file)
		if err != nil {
			fmt.Printf("Warning: skipping tags for %s: %v\n", cfg.registry, err)
			continue
		}
		var tags map[string]tagJSON
		if err := json.Unmarshal(data, &tags); err != nil {
			fmt.Printf("Warning: failed to parse %s: %v\n", cfg.file, err)
			continue
		}

		// Resolve all tags
		resolved := resolveAllTags(tags, cfg.ids)

		// Sort tag names for deterministic output
		tagNames := make([]string, 0, len(resolved))
		for name := range resolved {
			tagNames = append(tagNames, name)
		}
		sort.Strings(tagNames)

		sb.WriteString(fmt.Sprintf("\t{%q, []TagDef{\n", cfg.registry))
		for _, name := range tagNames {
			entries := resolved[name]
			if len(entries) == 0 {
				continue
			}
			totalTags++
			sb.WriteString(fmt.Sprintf("\t\t{%q, []int32{", "minecraft:"+name))
			for i, id := range entries {
				if i > 0 {
					sb.WriteString(", ")
				}
				sb.WriteString(fmt.Sprintf("%d", id))
			}
			sb.WriteString("}},\n")
		}
		sb.WriteString("\t}},\n")
	}
	sb.WriteString("}\n")

	os.WriteFile("internal/world/tags_generated.go", []byte(sb.String()), 0644)
	fmt.Printf("Generated tags: %d tag groups across %d registries\n", totalTags, len(configs))
}

func loadNameIDMap(path string) map[string]int {
	data, err := os.ReadFile(path)
	if err != nil {
		panic(fmt.Sprintf("failed to read %s: %v", path, err))
	}
	var entries []struct {
		ID   int    `json:"id"`
		Name string `json:"name"`
	}
	json.Unmarshal(data, &entries)
	m := make(map[string]int, len(entries))
	for _, e := range entries {
		m["minecraft:"+e.Name] = e.ID
	}
	return m
}

func resolveAllTags(tags map[string]tagJSON, ids map[string]int) map[string][]int32 {
	resolved := make(map[string][]int32)
	for name := range tags {
		resolveTag(name, tags, ids, resolved, make(map[string]bool))
	}
	return resolved
}

func resolveTag(name string, tags map[string]tagJSON, ids map[string]int, resolved map[string][]int32, visiting map[string]bool) []int32 {
	if entries, ok := resolved[name]; ok {
		return entries
	}
	if visiting[name] {
		return nil // circular reference
	}
	visiting[name] = true

	tag, ok := tags[name]
	if !ok {
		return nil
	}

	seen := make(map[int32]bool)
	var result []int32

	for _, value := range tag.Values {
		if strings.HasPrefix(value, "#") {
			// Tag reference: #minecraft:tag_name
			refName := value[1:] // strip #
			refName = strings.TrimPrefix(refName, "minecraft:")
			refIDs := resolveTag(refName, tags, ids, resolved, visiting)
			for _, id := range refIDs {
				if !seen[id] {
					seen[id] = true
					result = append(result, id)
				}
			}
		} else {
			// Direct entry
			if id, ok := ids[value]; ok {
				id32 := int32(id)
				if !seen[id32] {
					seen[id32] = true
					result = append(result, id32)
				}
			}
		}
	}

	resolved[name] = result
	return result
}

// === Full Registry Data Generation (JSON→NBT) ===

// Fields that must be Double (not Float) in NBT
var doubleFields = map[string]bool{
	"coordinate_scale": true,
	"offset":           true, // biome mood_sound
}

// Fields that must be Long (not Int) in NBT
var longFields = map[string]bool{
	"fixed_time": true,
}

func generateFullRegistryData(syncedNames []string) {
	// Map from syncedNames key to JSON data file
	dataFiles := map[string]string{
		"dimension_type":   "tools/data/registries/dimension_type.json",
		"worldgen/biome":   "tools/data/registries/biome.json",
		"chat_type":        "tools/data/registries/chat_type.json",
		"damage_type":      "tools/data/registries/damage_type.json",
		"banner_pattern":   "tools/data/registries/banner_pattern.json",
		"painting_variant": "tools/data/registries/painting_variant.json",
		"wolf_variant":     "tools/data/registries/wolf_variant.json",
		"enchantment":      "tools/data/registries/enchantment.json",
		"jukebox_song":     "tools/data/registries/jukebox_song.json",
		"trim_pattern":     "tools/data/registries/trim_pattern.json",
		"trim_material":    "tools/data/registries/trim_material.json",
		"instrument":       "tools/data/registries/instrument.json",
	}

	var sb strings.Builder
	sb.WriteString("// Code generated by tools/gen_registry. DO NOT EDIT.\n")
	sb.WriteString("package world\n\n")
	sb.WriteString("// RegistryEntryData holds pre-encoded NBT data for a single registry entry.\n")
	sb.WriteString("type RegistryEntryData struct {\n")
	sb.WriteString("\tName string\n")
	sb.WriteString("\tData []byte\n")
	sb.WriteString("}\n\n")
	sb.WriteString("// FullRegistryData contains full NBT data for all synced registries.\n")
	sb.WriteString("// Used when the client does not match known packs (cross-version).\n")
	sb.WriteString("var FullRegistryData = []struct {\n")
	sb.WriteString("\tID      string\n")
	sb.WriteString("\tEntries []RegistryEntryData\n")
	sb.WriteString("}{\n")

	totalEntries := 0
	for _, name := range syncedNames {
		dataFile, ok := dataFiles[name]
		if !ok {
			continue
		}
		raw, err := os.ReadFile(dataFile)
		if err != nil {
			fmt.Printf("Warning: no full data for %s: %v\n", name, err)
			continue
		}

		// Parse with json.Number to preserve number types
		var entries map[string]interface{}
		dec := json.NewDecoder(bytes.NewReader(raw))
		dec.UseNumber()
		if err := dec.Decode(&entries); err != nil {
			fmt.Printf("Warning: failed to parse %s: %v\n", dataFile, err)
			continue
		}

		// Sort entry names for deterministic output (matches SyncedRegistries order)
		entryNames := make([]string, 0, len(entries))
		for k := range entries {
			entryNames = append(entryNames, k)
		}
		sort.Strings(entryNames)

		sb.WriteString(fmt.Sprintf("\t{%q, []RegistryEntryData{\n", "minecraft:"+name))
		for _, entryName := range entryNames {
			entryData := entries[entryName].(map[string]interface{})
			nbtBytes := encodeRegistryNBT(entryData)
			totalEntries++
			sb.WriteString(fmt.Sprintf("\t\t{%q, []byte{", "minecraft:"+entryName))
			for i, b := range nbtBytes {
				if i > 0 {
					sb.WriteString(", ")
				}
				sb.WriteString(fmt.Sprintf("0x%02x", b))
			}
			sb.WriteString("}},\n")
		}
		sb.WriteString("\t}},\n")
	}
	sb.WriteString("}\n")

	os.WriteFile("internal/world/registry_data_generated.go", []byte(sb.String()), 0644)
	fmt.Printf("Generated full registry data: %d entries\n", totalEntries)
}

// encodeRegistryNBT encodes a JSON object as anonymous NBT compound (network format).
func encodeRegistryNBT(data map[string]interface{}) []byte {
	var buf bytes.Buffer
	buf.WriteByte(0x0a) // TagCompound root (anonymous)
	writeNBTCompound(&buf, data)
	return buf.Bytes()
}

func writeNBTCompound(buf *bytes.Buffer, data map[string]interface{}) {
	keys := make([]string, 0, len(data))
	for k := range data {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, name := range keys {
		value := data[name]
		if value == nil {
			continue
		}
		tagType := inferNBTType(name, value)
		if tagType == 0 {
			continue
		}
		buf.WriteByte(tagType)
		writeNBTString(buf, name)
		writeNBTPayloadGen(buf, tagType, name, value)
	}
	buf.WriteByte(0x00) // TagEnd
}

func writeNBTString(buf *bytes.Buffer, s string) {
	b := make([]byte, 2)
	binary.BigEndian.PutUint16(b, uint16(len(s)))
	buf.Write(b)
	buf.WriteString(s)
}

func writeNBTPayloadGen(buf *bytes.Buffer, tagType byte, fieldName string, value interface{}) {
	switch tagType {
	case 1: // Byte
		if v, ok := value.(bool); ok {
			if v {
				buf.WriteByte(1)
			} else {
				buf.WriteByte(0)
			}
		} else if n, ok := value.(json.Number); ok {
			i, _ := n.Int64()
			buf.WriteByte(byte(i))
		}
	case 3: // Int
		n := value.(json.Number)
		i, _ := n.Int64()
		b := make([]byte, 4)
		binary.BigEndian.PutUint32(b, uint32(int32(i)))
		buf.Write(b)
	case 4: // Long
		n := value.(json.Number)
		i, _ := n.Int64()
		b := make([]byte, 8)
		binary.BigEndian.PutUint64(b, uint64(i))
		buf.Write(b)
	case 5: // Float
		n := value.(json.Number)
		f, _ := n.Float64()
		b := make([]byte, 4)
		binary.BigEndian.PutUint32(b, math.Float32bits(float32(f)))
		buf.Write(b)
	case 6: // Double
		n := value.(json.Number)
		f, _ := n.Float64()
		b := make([]byte, 8)
		binary.BigEndian.PutUint64(b, math.Float64bits(f))
		buf.Write(b)
	case 8: // String
		writeNBTString(buf, value.(string))
	case 9: // List
		arr := value.([]interface{})
		if len(arr) == 0 {
			buf.WriteByte(0) // element type: End
			b := make([]byte, 4)
			buf.Write(b) // count: 0
		} else {
			elemType := inferNBTType("", arr[0])
			buf.WriteByte(elemType)
			b := make([]byte, 4)
			binary.BigEndian.PutUint32(b, uint32(len(arr)))
			buf.Write(b)
			for _, elem := range arr {
				writeNBTPayloadGen(buf, elemType, "", elem)
			}
		}
	case 10: // Compound
		writeNBTCompound(buf, value.(map[string]interface{}))
	}
}

func inferNBTType(fieldName string, value interface{}) byte {
	switch v := value.(type) {
	case bool:
		return 1 // Byte
	case json.Number:
		s := v.String()
		if strings.Contains(s, ".") || strings.ContainsAny(s, "eE") {
			if doubleFields[fieldName] {
				return 6 // Double
			}
			return 5 // Float
		}
		if longFields[fieldName] {
			return 4 // Long
		}
		return 3 // Int
	case string:
		return 8 // String
	case []interface{}:
		return 9 // List
	case map[string]interface{}:
		return 10 // Compound
	}
	return 0 // Unknown
}
