// Tool to generate block state and biome registry data from PrismarineJS minecraft-data.
// Usage: go run tools/gen_registry/main.go
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

type block struct {
	ID           int     `json:"id"`
	Name         string  `json:"name"`
	MinStateID   int     `json:"minStateId"`
	MaxStateID   int     `json:"maxStateId"`
	DefaultState int     `json:"defaultState"`
	States       []state `json:"states"`
}

type state struct {
	Name      string   `json:"name"`
	Type      string   `json:"type"`
	NumValues int      `json:"num_values"`
	Values    []string `json:"values"`
}

type biome struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

func main() {
	blocksData, err := os.ReadFile("tools/data/blocks.json")
	if err != nil {
		panic(err)
	}
	biomesData, err := os.ReadFile("tools/data/biomes.json")
	if err != nil {
		panic(err)
	}

	var blocks []block
	var biomes []biome
	json.Unmarshal(blocksData, &blocks)
	json.Unmarshal(biomesData, &biomes)

	var sb strings.Builder
	sb.WriteString("// Code generated by tools/gen_registry. DO NOT EDIT.\n")
	sb.WriteString("package world\n\n")

	// Block registry
	sb.WriteString("type blockDef struct {\n")
	sb.WriteString("\tMinStateID   int\n")
	sb.WriteString("\tDefaultState int\n")
	sb.WriteString("\tProperties   []propDef\n")
	sb.WriteString("}\n\n")
	sb.WriteString("type propDef struct {\n")
	sb.WriteString("\tName   string\n")
	sb.WriteString("\tValues []string\n")
	sb.WriteString("}\n\n")

	sb.WriteString("var blockRegistry = map[string]blockDef{\n")
	for _, b := range blocks {
		sb.WriteString(fmt.Sprintf("\t%q: {%d, %d, ", "minecraft:"+b.Name, b.MinStateID, b.DefaultState))
		if len(b.States) == 0 {
			sb.WriteString("nil},\n")
		} else {
			sb.WriteString("[]propDef{")
			for i, s := range b.States {
				if i > 0 {
					sb.WriteString(", ")
				}
				values := s.Values
				if s.Type == "bool" && len(values) == 0 {
					values = []string{"true", "false"}
				}
				sb.WriteString(fmt.Sprintf("{%q, []string{", s.Name))
				for j, v := range values {
					if j > 0 {
						sb.WriteString(", ")
					}
					sb.WriteString(fmt.Sprintf("%q", v))
				}
				sb.WriteString("}}")
			}
			sb.WriteString("}},\n")
		}
	}
	sb.WriteString("}\n\n")

	// Biome registry
	sort.Slice(biomes, func(i, j int) bool { return biomes[i].ID < biomes[j].ID })
	sb.WriteString("var biomeRegistry = map[string]int{\n")
	for _, b := range biomes {
		sb.WriteString(fmt.Sprintf("\t%q: %d,\n", "minecraft:"+b.Name, b.ID))
	}
	sb.WriteString("}\n")

	// Synced registries (must be sent during configuration even with Known Packs)
	registriesData, err := os.ReadFile("tools/data/registries.json")
	if err != nil {
		panic(err)
	}
	var registries map[string][]string
	json.Unmarshal(registriesData, &registries)

	syncedNames := []string{
		"dimension_type", "worldgen/biome", "chat_type", "damage_type",
		"banner_pattern", "painting_variant", "wolf_variant",
		"enchantment", "jukebox_song", "trim_pattern", "trim_material", "instrument",
	}

	sb.WriteString("\n// SyncedRegistries lists registries that must be sent via Registry Data during configuration.\n")
	sb.WriteString("// Entry keys are listed so the server can send has_data=false when Known Packs match.\n")
	sb.WriteString("var SyncedRegistries = []struct {\n")
	sb.WriteString("\tID      string\n")
	sb.WriteString("\tEntries []string\n")
	sb.WriteString("}{\n")

	totalEntries := 0
	for _, name := range syncedNames {
		entries, ok := registries[name]
		if !ok {
			continue
		}
		sort.Strings(entries)
		totalEntries += len(entries)
		sb.WriteString(fmt.Sprintf("\t{%q, []string{\n", "minecraft:"+name))
		for _, e := range entries {
			sb.WriteString(fmt.Sprintf("\t\t%q,\n", "minecraft:"+e))
		}
		sb.WriteString("\t}},\n")
	}
	sb.WriteString("}\n")

	os.WriteFile("internal/world/registry_generated.go", []byte(sb.String()), 0644)
	fmt.Printf("Generated registry: %d blocks, %d biomes, max state ID %d, %d synced registry entries\n",
		len(blocks), len(biomes), blocks[len(blocks)-1].MaxStateID, totalEntries)
}
